# Generated by Django 4.0.3 on 2022-04-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_master',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
