# Generated by Django 4.0.3 on 2022-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_signup_master_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_master',
            name='zipcode',
            field=models.BigIntegerField(),
        ),
    ]
