# Generated by Django 4.0.3 on 2022-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_signup_master_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_master',
            name='otp',
            field=models.IntegerField(default=234576),
            preserve_default=False,
        ),
    ]
